### ISSUE TITLE
AnyValue

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-proto#167]
I’m trying to update to latest proto and I’m having a hard time with oneof value for AnyValue and testing that
Could you please correct me if I'm wrong .

Let say I have a span with following attributes
```
const span = {
  attributes: [{
    myParam: 'foo'  
  }]
}
```

In previous version the attribute looked like
```
const span = {
  attributes: [{
    key: 'myParam',
    stringValue: 'foo'
  }]
}
```

How the span should look like ?
I tried all different cases, nothing works except old format

1. This is how it should be (if I understand correctly)
```
{
  key: 'myParam',
  value: {
    stringValue: "foo"
  }
}
```
Error: `(proto: wrong wireType = 2 for field Type(proto: wrong wireType = 2 for field Type`

2. 
```
{
  key: 'myParam',
  stringValue: 'foo'
}
```
No error, but value is not present in zipkin

3.
```
{
  key: 'myParam',
  type: 0, // or 'STRING'
  stringValue: 'foo'
}
```
No error, but value is not present in zipkin

4.  

```
{
  key: 'myParam',
  value: 'foo'
}
```
Error: `(proto: wrong wireType = 2 for field Type(proto: wrong wireType = 2 for field Type`

5.  

```
{
  key: 'myParam',
  type: 0, // 'STRING'
  value: 'foo'
}
```
Error: `(proto: wrong wireType = 2 for field Type(proto: wrong wireType = 2 for field Type`

6. 
```
{
  value: {
    key: 'myParam',
    stringValue: 'foo'
  }
}
```
Error: `(proto: wrong wireType = 2 for field Type(proto: wrong wireType = 2 for field Type`

For me it looks like new format is not available yet ?, only old is respected but the value of tag is not shown anyway in zipkin 

And as last I tried this
```
  span.setAttribute('mapAndArrayValue', [
    0,1,2.25, 'alicja',  {
      foo: 'bar',
      baz: 'bara',
      array: [1,2,'aaa']
    }
  ]);
```
It was accepted but in zipkin only tag name has been shown
```
'attributes': [{
            'key': 'key',
            'stringValue': 'value'
          }, {
            'key': 'mapAndArrayValue',
            'arrayValue': {
              'valuesList': [{ 'doubleValue': 0 }, { 'doubleValue': 1 }, { 'doubleValue': 2.25 }, { 'stringValue': 'alicja' }, {
                'kvlistValue': {
                  'valuesList': [{
                    'key': 'foo',
                    'stringValue': 'bar'
                  }, { 'key': 'baz', 'stringValue': 'bara' }, {
                    'key': 'array',
                    'arrayValue': { 'valuesList': [{ 'doubleValue': 1 }, { 'doubleValue': 2 }, { 'stringValue': 'aaa' }] }
                  }]
                }
              }]
            }
          }]
```

So main question does the "oneOf" nothing change in fact, or the format is not fully implemented or ?.
Why the values for tags are not shown in zipkin ?

**Comment by obecny** [comment]
ok I have figured that myself
the correct attributes should look like 


```
{
  key: 'myParam',
  value: 'stringValue',
  stringValue: 'foo'
}
```

so the value needs to point to what has been chosen

**Comment by obecny** [comment]
ok here are my findings:
1. For json over http this is fine
```
{
  key: 'myParam',
  value: 'stringValue',
  stringValue: 'foo'
}
```
2. For grpc or proto over http I cannot force it to work, however I debugged things with serializing proto and such structure is serialising correctly
```
{
  key: 'myParam',
  value: {
    stringValue: 'foo'
  }
}
```

Here are my collector files
```
version: "3"
services:
  # Collector
  collector:
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/conf/collector-config.yaml", "--log-level=DEBUG"]
    networks:
      - otelcol
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "55680:55680"
    depends_on:
      - zipkin-all-in-one

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    networks:
      - otelcol
    ports:
      - "9411:9411"

networks:
  otelcol:

```
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    url: "http://zipkin-all-in-one:9411/api/v2/spans"

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch, queued_retry]
```

From grpc I'm getting error
```
{
  "code": 13,
  "metadata": {
    "_internal_repr": {},
    "flags": 0
  },
  "details": "grpc: error unmarshalling request: proto: wrong wireType = 2 for field Type"
}
```

Any suggestions thoughts ?
